import pytest
import requests

from automation_business_scaffold.infrastructure.fastmoss.http_session import (
    FastMossHTTPSession, build_fm_sig,
)


# Generated by current frontend module 877830 using synthetic, credential-free inputs.
VECTORS = [{'path': '/api/author/v3/detail/baseInfo',
  'params': {'uid': '123', '_time': 1789286400, 'cnonce': '12345678'},
  'source': 'pc',
  'expected': '4s92azflk05yqb3pcyte25rbw8taavz9gmhimhzl4sd0m5vzg49ke3bd029oyz3l'},
 {'path': '/api/goods/V2/search',
  'params': {'words': 'tea & 咖啡~!*', 'page': 1, '_time': 1789286401, 'cnonce': '98765432'},
  'source': 'pc',
  'expected': 'sox66bf106p0y7bx0q1syx3jk41oqnj7km5wunvj0idyi5ztgs9aadn10e1g6ff1'},
 {'path': '/api/author/v3/detail/baseInfo',
  'params': {'uid': '123', '_time': 1789286402, 'cnonce': '22345678'},
  'source': 'pc',
  'expected': '4s92azflk05yqb3pc2teybvl8o9aavz9gmhimhzl4sd0m5jzg49kar3x02toyz3l'},
 {'path': '/api/user/login',
  'params': {'_time': 1789286403, 'cnonce': '00001234'},
  'source': 'pc',
  'expected': 'g46nq1378kuniff74gqbezvhssih6pn3ciuzinvdwsqna9vd4a6z6pfvw6qtq9rf'},
 {'path': '/api/goods/V2/search',
  'params': {'page': 0, 'words': '', '_time': 1789286404, 'cnonce': '99112233'},
  'source': 'other',
  'expected': 'so12ax3rguh82d3xosxw61zlkkt82fbr8ol6q5j1k2twq7j58yh8axj1c6pw2jjz'}]


@pytest.mark.parametrize("vector", VECTORS)
def test_fm_sig_matches_current_frontend(vector):
    assert build_fm_sig(vector["path"], vector["params"], source=vector["source"]) == vector["expected"]


def test_http_retry_regenerates_both_signatures_from_actual_query(monkeypatch):
    calls = []
    nonces = iter(["12345678", "22345678"])
    response = requests.Response()
    response.status_code = 200
    response._content = b'{"code":200,"data":{},"ext":{"is_login":1}}'

    def request(**kwargs):
        calls.append(kwargs)
        if len(calls) == 1:
            raise requests.Timeout("simulated")
        return response

    with FastMossHTTPSession(time_factory=lambda: 1789286400, nonce_factory=lambda: next(nonces),
                            request_delay_range=(0, 0), sleep_factory=lambda _: None) as client:
        monkeypatch.setattr(client.session, "request", request)
        client.request_json("GET", VECTORS[0]["path"], params={"uid": "123"},
                            headers={"fm-sig": "stale"}, check_auth=False, retries=2)
    assert len(calls) == 2
    assert calls[0]["headers"]["fm-sig"] == VECTORS[0]["expected"]
    assert calls[0]["params"]["cnonce"] != calls[1]["params"]["cnonce"]
    assert calls[0]["headers"]["fm-sign"] != calls[1]["headers"]["fm-sign"]
    assert calls[0]["headers"]["fm-sig"] != calls[1]["headers"]["fm-sig"]
    assert calls[1]["headers"]["fm-sig"] == build_fm_sig(VECTORS[0]["path"], calls[1]["params"])


def test_explicit_unsigned_request_preserves_existing_behavior(monkeypatch):
    calls = []
    response = requests.Response()
    response.status_code = 200
    response._content = b'{"code":200,"data":{}}'
    with FastMossHTTPSession(request_delay_range=(0, 0)) as client:
        monkeypatch.setattr(client.session, "request", lambda **kw: calls.append(kw) or response)
        client.request_json("POST", "/api/user/login", json_body={"example": "synthetic"},
                            sign_request=False, check_auth=False, retries=1)
    assert "fm-sign" not in calls[0]["headers"]
    assert "fm-sig" not in calls[0]["headers"]


def test_product_video_discovery_uses_both_signatures(monkeypatch):
    calls = []
    response = requests.Response()
    response.status_code = 200
    response._content = b'{"code":200,"data":{"list":[]},"ext":{"is_login":1}}'
    with FastMossHTTPSession(request_delay_range=(0, 0)) as client:
        monkeypatch.setattr(client.session, "request", lambda **kw: calls.append(kw) or response)
        client.list_product_videos("123", pagesize=5, order="1,2", d_type=0,
                                   date_type=28, is_promoted=-1)
    assert calls[0]["headers"].get("fm-sign")
    assert calls[0]["headers"].get("fm-sig") == build_fm_sig(
        "/api/goods/v3/video", calls[0]["params"],
    )
